import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeInitScript } from './lib/ThemeInitScript'
import Script from 'next/script'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Deliberately minimal — this wraps BOTH route groups, the public site
 * (app/(site)) and the admin CMS (app/admin), which intentionally do not
 * share chrome, locale/theme/sound providers, or page-transition behavior.
 * Only truly global concerns (fonts, the no-FOUC accent-color script,
 * <html>/<body>) belong here; everything else lives in each group's own
 * nested layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <ThemeInitScript />
        {/* Eir script-ta puro site-e right-click off kore debe */}
        <Script id="disable-right-click" strategy="afterInteractive">
          {`document.addEventListener('contextmenu', event => event.preventDefault());`}
        </Script>
      </head>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}